### ISSUE TITLE
Cannot install multi backend (ROCm) Wheel version does not match filename

### ISSUE THREAD

**Issue by RSWilli** [bitsandbytes-foundation/bitsandbytes#1473]
### System Info

AMD RX 7800 XT

python
3.11.10

torch
2.4.1+rocm6.1

torchvision
0.19.1+rocm6.1

transformers
4.46.3

### Reproduction

I am trying to get the https://github.com/invoke-ai/InvokeAI/issues/7535 docker container to run for my GPU. bitsandbytes does not seem to be installed with the multi backend support, so I'm fiddling around in the docker file with the following command:

```
RUN uv pip install --python ${PYTHON_VERSION} --no-deps 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.44.1.dev0-py3-none-manylinux_2_24_x86_64.whl'
```

And the command always gives me the following:

```
Wheel version does not match filename: 0.44.1.dev0+9315692 != 0.44.1.dev0
```

I do have the `HSA_OVERRIDE_GFX_VERSION=11.0.0` env var set.

### Expected behavior

it installs

**Comment by akx** [comment]
What's the version of `uv` in your Docker image? This should have been fixed: https://github.com/astral-sh/uv/issues/3594

**Comment by RSWilli** [comment]
the dockerfile used the tag 0.5.5 of https://github.com/astral-sh/uv/pkgs/container/uv

I tried 0.5.24, but the same problem persists

**Comment by TimDettmers** [comment]
Closing this issue. The wheel version mismatch (`0.44.1.dev0+9315692 != 0.44.1.dev0`) is a packaging tool issue, not a bitsandbytes bug. The commenter linked to the relevant uv fix (https://github.com/astral-sh/uv/issues/3594). If newer uv versions still don't work, try installing with pip instead, or use the current release wheels rather than the dev multi-backend build.
