### ISSUE TITLE
libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by aholovenko** [bitsandbytes-foundation/bitsandbytes#1584]
Get an error when running bitsandbytes import in the package that is dependent on bitsandbytes
```
import bitsandbytes as bnb
```
Package: https://github.com/SeanLee97/AnglE in `angle.py:line 16`

Full error tranceback:
```
Could not load bitsandbytes native library: /home/username/.pyenv/versions/my_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/username/.pyenv/versions/my_venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 85, in <module>
    lib = get_native_library()
  File "/home/username/.pyenv/versions/my_venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 72, in get_native_library
    dll = ct.cdll.LoadLibrary(str(binary_path))
  File "/home/username/.pyenv/versions/3.10.14/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/home/username/.pyenv/versions/3.10.14/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/username/.pyenv/versions/my_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: cannot open shared object file: No such file or directory
```

Any ideas why this might be happening?
```
angle_emb==0.5.6
bitsandbytes==0.45.4
```
Python version os 3.10.14.
Ubuntu version 24.04.1 LTS

Would be thankful for any assistance :)

**Comment by vindex10** [comment]
Also, `libbitsandbytes_cpu.so` is present in `bitsandbytes==0.45.2`

**Comment by Titus-von-Koeller** [comment]
Thanks for raising this, true, a recent change in the build introduced this bug. We're in the process of fixing this and releasing asap.

**Comment by matthewdouglas** [comment]
We've pushed a new release to fix this. Thanks!
`pip install -U bitsandbytes==0.45.5`

**Comment by VarunGumma** [comment]
I still get the same issue when I install from the `multi-backend-refactor` branch. 

Is there any solution for this? I am trying to build `bnb` from source in an ROCm based image.
